# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pr:
  - master



jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - bash: 'brew install pkg-config'
  - bash: 'brew install libpng'
  - bash: 'sudo xcode-select -s /Applications/Xcode_12.4.app/Contents/Developer'
  - bash: 'swift --version'
  - bash: 'swift test'

- job: Linux
  container:
    image: swift:5.4.3
    options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      /tmp/docker exec -t -u 0 ci-container \
      sh -c "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" -y install sudo"
    displayName: Set up sudo
  - script: 'sudo apt-get update'
  - script: 'sudo apt-get install zlib1g-dev'
  - bash: 'swift --version'
  - bash: 'swift test'

- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      REM Derived from: https://gist.github.com/devhawk/2d8cb579f179ed659e3862c860d846d6
      set vswherepath="%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
      for /f "usebackq delims=" %%i in (`%vswherepath% -latest -property installationPath`) do (
          set vslatest="%%i"
          if exist "%%i\VC\Auxiliary\Build\vcvars64.bat" (
              set vcvars64="%%i\VC\Auxiliary\Build\vcvars64.bat"
          )
      )
      
      @echo vslatest %vslatest%
      @echo vcvars64 %vcvars64%
      
      call %vcvars64%
      
      REM Derived from: https://github.com/SDGGiesbrecht/SDGCornerstone/blob/955d54feae736122e2f6af4887c2cfaef468870a/.github/workflows/Windows.yaml
      
      copy %SDKROOT%\usr\share\ucrt.modulemap "%UniversalCRTSdkDir%\Include\%UCRTVersion%\ucrt\module.modulemap"
      copy %SDKROOT%\usr\share\visualc.modulemap "%VCToolsInstallDir%\include\module.modulemap"
      copy %SDKROOT%\usr\share\visualc.apinotes "%VCToolsInstallDir%\include\visualc.apinotes"
      copy %SDKROOT%\usr\share\winsdk.modulemap "%UniversalCRTSdkDir%\Include\%UCRTVersion%\um\module.modulemap"
      
      set Path=C:\Library\icu-67\usr\bin;%Path%
      set Path=C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin;%Path%
      set Path=C:\Library\Swift-development\bin;%Path%
      set Path=C:\Library\Developer\Platforms\Windows.platform\Developer\Library\XCTest-development\usr\bin;%Path%
      
      swift test ^
          -Xswiftc -I -Xswiftc C:\Library\Developer\Platforms\Windows.platform\Developer\Library\XCTest-development\usr\lib\swift\windows\x86_64 ^
          -Xswiftc -L -Xswiftc C:\Library\Developer\Platforms\Windows.platform\Developer\Library\XCTest-development\usr\lib\swift\windows
