# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - bash: 'brew install pkg-config'
  - bash: 'brew install libpng'
  - bash: 'swift test'

- job: Linux
  container: swift:5.0-xenial
  pool:
    vmImage: ubuntu-16.04
  steps:
  - bash: 'swift test'
