#if !canImport(ObjectiveC)
import XCTest

extension LibPNGTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LibPNGTests = [
        ("testFromRgba", testFromRgba),
        ("testReadFromFile", testReadFromFile),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LibPNGTests.__allTests__LibPNGTests),
    ]
}
#endif
